spring:
  security:
    user:
      name: user
      password: user
  application:
    name: Student-Service
  banner:
    location: classpath:banner.txt
  datasource:
    url: jdbc:postgresql://localhost:5432/Student
    username: postgres
    password: sourya3110
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  main:
    banner-mode: off


app:
  message: "Welcome To Student Service System"
  author: "Souryadeep"
logging:
  level:
    org:
      springframework:
        boot:
          devtools: DEBUG

server:
  address: 0.0.0.0
  port: 8080
grpc:
  server:
    name: Student-Service
    port: 9090
    enable-reflection: true
    certificateChain: classpath:server.crt
    privateKey: classpath:server.key